name: Daily AI Article

on:
  schedule:
    - cron: '0 4 * * *'  # 每天北京时间中午 12 点
  workflow_dispatch:

jobs:
  generate-article:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Generate AI article
      run: npm run gen:prod
      env:
        NODE_ENV: production

    - name: Build VuePress site
      run: npm run docs:build
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/.vuepress/dist
        force_orphan: true
        
    - name: Commit generated files
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const { execSync } = require('child_process');
          
          // 配置git用户信息
          execSync('git config --global user.name "GitHub Actions"');
          execSync('git config --global user.email "actions@github.com"');
          
          // 添加所有更改
          execSync('git add .');
          
          // 检查是否有更改需要提交
          const status = execSync('git status --porcelain').toString();
          if (status) {
            execSync(`git commit -m "Auto-commit generated files on ${new Date().toISOString()}"`);
            execSync('git push origin main');
          }
